const REGISTER_INFO_IS_REQUIRED = "REGISTER_INFO_IS_REQUIRED"
const USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
const ROLE_DOES_NOT_EXIST = "ROLE_DOES_NOT_EXIST"
const LOGIN_INFO_IS_REQUIRED = "LOGIN_INFO_IS_REQUIRED"
const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
const PASSWORD_IS_INCURRECT = "PASSWORD_IS_INCURRECT"
const UNAUTHORIZATION = "UNAUTHORIZATION"

module.exports = {
  REGISTER_INFO_IS_REQUIRED,
  USER_ALREADY_EXIST,
  ROLE_DOES_NOT_EXIST,
  LOGIN_INFO_IS_REQUIRED,
  USER_DOES_NOT_EXIST,
  PASSWORD_IS_INCURRECT,
  UNAUTHORIZATION
}